name: amin_test
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  app_tutorial: ^1.0.6
  flutter:
    sdk: flutter

  image_picker: ^0.8.7
  image_cropper: ^4.0.1
  path_provider: ^2.0.15
  permission_handler: ^10.2.0
  http: ^0.13.6


dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
